### ISSUE TITLE
Atlas ctest failure in ectrans

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#118]
One of the atlas ctests (atlas_test_functionspace) is failing in ectrans:

142: Runtime Error: /home/h01/frwd/cylc-run/mi-be984/work/1/ecbuild_ectrans_nag/build/src/trans/generated/ectrans_dp/internal/tpm_fftw.F90, line 231: Reference to disassociated POINTER TW%FFTW_PLANS
142: Program terminated by fatal error

**Comment by samhatfield** [comment]
Thanks, I'll take a look soon.
