### ISSUE TITLE
Intel compile failure from illegal code

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#13]
I am getting compile failures with Intel, for example

/home/d03/frwd/cylc-run/AddEctransFiat/share/mo-bundle/ectrans/src/trans/internal/ftdirad_mod.F90(92): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [A]
    CALL FFT992(PREEL(1,IOFF),T%TRIGS(1,KGL),&

**Comment by wdeconinck** [comment]
Hi @DJDavies2  thank you for this report.
In order for us to reproduce, which environment, architecture and version of Intel compiler is being used?
We already have a continuous integration in place using Intel OneAPI which is not failing like that
(e.g. https://github.com/ecmwf-ifs/ectrans/actions/runs/3512552361/jobs/5884373860).
