### ISSUE TITLE
ctest failure in ectrans_test_adjoint

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#15]
Running the ctests results in this failure:

        Start   8: ectrans_test_benchmark_dp_T47_O48_mpi0_omp1_nfld10_nlev20_vordiv_uvders
  1/156 Test   #2: ectrans_test_adjoint ......................................................***Failed    0.51 sec
  NSMAX=           21
  NDGL=          32
  LMPOFF=  T
  NSPEC2=         506
  NGPTOT=        2048
  NFLEV=           9
 SETUP FINISHED
forrtl: severe (408): fort: (3): Subscript #1 of the array A has value -26 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002B53F837E2C9  for_emit_diagnost     Unknown  Unknown
libtrans_dp.so     00002B53F9A9BA48  fft992_IP_rpassf_         483  fft992.F90
libtrans_dp.so     00002B53F9A98DF3  fft992_                   235  fft992.F90
libtrans_dp.so     00002B53F9CC6B94  ftinv_mod_mp_ftin          94  ftinv_mod.F90
libtrans_dp.so     00002B53F9CBC608  ftinv_ctl_mod_mp_         193  ftinv_ctl_mod.F90
libiomp5.so        00002B53F8041A43  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002B53F80052C6  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002B53F7FC4BB0  __kmpc_fork_call      Unknown  Unknown
libtrans_dp.so     00002B53F9CB780E  ftinv_ctl_mod_mp_         178  ftinv_ctl_mod.F90
libtrans_dp.so     00002B53F9D0E84E  inv_trans_ctl_mod         288  inv_trans_ctl_mod.F90
libtrans_dp.so     00002B53F9F5257D  inv_trans_                610  inv_trans.F90
ectrans_test_adjo  000000000040AD26  MAIN__                    197  test_adjoint.F90
ectrans_test_adjo  0000000000401BA2  Unknown               Unknown  Unknown
libc-2.17.so       00002B53FB1C8555  __libc_start_main     Unknown  Unknown
ectrans_test_adjo  0000000000401AB9  Unknown               Unknown  Unknown

This failure occurs with Intel compilers.  Gnu compilers seem to work.

**Comment by wdeconinck** [comment]
Could this have been related to your commits introduced with PR #14 ?
In following line and other similar lines in that PR, could you replace `PREEL(1:,IOFF)` with `PREEL(:,IOFF)` and see if it works?
https://github.com/ecmwf-ifs/ectrans/blob/main/src/trans/internal/ftinv_mod.F90#L94
I don't see any failures with our intel compilers so I cannot test this problem.

**Comment by DJDavies2** [comment]
I have proposed something in #16.  I am guessing that the alignment of the arguments is wrong as things stand and turning the actual arguments into proper 2d arguments is the way to make them correct.

The lower bounds of PREEL are already 1 so there is no need to specify it explicitly.

**Comment by wdeconinck** [comment]
Thank you @DJDavies2  for the proposed fix. This is now merged.
