### ISSUE TITLE
Intel failure in butterfly_alg_mod.F90

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#17]
Another failure building with Intel:

ectrans_test_benchmark_dp_T47_O48_mpi0_omp1_nfld10_nlev20_flt

forrtl: severe (151): allocatable array is already allocated
Image              PC                Routine            Line        Source             
ectrans-benchmark  0000000000479EB7  Unknown               Unknown  Unknown
libtrans_dp.so     00002BA9E810BAC3  butterfly_alg_mod         188  butterfly_alg_mod.F90
libiomp5.so        00002BA9EFF79A43  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002BA9EFF3D2C6  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002BA9EFEFCBB0  __kmpc_fork_call      Unknown  Unknown
libtrans_dp.so     00002BA9E80F979F  butterfly_alg_mod         179  butterfly_alg_mod.F90
libtrans_dp.so     00002BA9E8515801  suleg_mod_mp_sule         790  suleg_mod.F90
libtrans_dp.so     00002BA9E86BE8E0  setup_trans_              406  setup_trans.F90
ectrans-benchmark  00000000004106AC  MAIN__                    397  ectrans-benchmark.F90
ectrans-benchmark  000000000040DC9E  Unknown               Unknown  Unknown
libc-2.11.3.so     00002BA9EF918C36  __libc_start_main     Unknown  Unknown
ectrans-benchmark  000000000040DB29  Unknown               Unknown  Unknown

This only shows with runtime checks on.

**Comment by DJDavies2** [comment]
In particular this is line 188:

        ALLOCATE(ZSUB(IROWS,ICOLS))

It appears to be related to the OpenMP stuff.  Commenting out the OpenMP lines results in the run succeeding.

**Comment by wdeconinck** [comment]
I have tried and could not reproduce.
Which compiler version and flags were used? What exactly did you mean with "runtime checks on"?

**Comment by DJDavies2** [comment]
The compiler is Intel 18, compile options are

/opt/intel/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort -DWITH_FFTW -Dtrans_dp_EXPORTS -I/home/d03/frwd/cylc-run/EctransFailures/share/mo-bundle/ectrans/src/trans/include -I/home/d03/frwd/cylc-run/EctransFailures/share/mo-bundle/ectrans/src/trans/include/ectrans -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/module/trans_dp -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/fiat/src -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/fiat/include -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/fiat/include/fiat -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/module/fiat -I/home/d03/frwd/cylc-run/EctransFailures/share/build-mo-cray_intel_debug/module/parkind_dp -I/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/include/fftw -I/opt/cray/mpt/7.5.3/gni/mpich-intel/16.0/include -g -O0 -traceback -warn -heap-arrays -check all -check noarg_temp_created -fp-model precise -fp-model source -module ../../../module/trans_dp -fPIC -qopenmp -c /home/d03/frwd/cylc-run/EctransFailures/share/mo-bundle/ectrans/src/trans/algor/butterfly_alg_mod.F90 -o CMakeFiles/trans_dp.dir/algor/butterfly_alg_mod.F90.o

**Comment by DJDavies2** [comment]
I've dug around with the compile options, it seems that the failure occurs with the -check pointers compile option.  The code was being compiled with -check all which includes -check pointers among other.  Changing from -check all to -check all -check nopointers results in the tests working.

Is it possible to change compile options for a specific file?

**Comment by climbfuji** [comment]
> I've dug around with the compile options, it seems that the failure occurs with the -check pointers compile option. The code was being compiled with -check all which includes -check pointers among other. Changing from -check all to -check all -check nopointers results in the tests working.
> 
> Is it possible to change compile options for a specific file?

https://github.com/ecmwf/ecbuild/issues/45

**Comment by DJDavies2** [comment]
Okay, that would mean editing the CMakeLists.txt for ectrans for a particular (old) version of the particular compiler for what looks like a compiler bug that has since been fixed.  That doesn't seem like it is worth doing so I'll close this issue.

**Comment by wdeconinck** [comment]
Thanks for getting to the bottom of this!

I have addressed this problem regardless in commit 7a002baf53b989a3c888e2462ff26f4444489537 in develop branch.
The Intel 18 compiler is still around here and there, even though it is quite old now.
It doesn't hurt and could always be removed in the future.
This commit just appends the "-check nopointers" flag per your suggestion.
Please confirm this is sufficient.

**Comment by DJDavies2** [comment]
Yes, the develop branch work, thanks for that.  Is this going to make it into a tagged release?
