### ISSUE TITLE
Add ecTrans versioning information print statement to SETUP_TRANS0

### ISSUE THREAD

**Issue by samhatfield** [ecmwf-ifs/ectrans#23]
It would be useful to be able to see the Git version of ecTrans printed to STDOUT in SETUP_TRANS0. I'm often playing with multiple branches at the same time so it's useful to verify that I'm using the one I think I'm using.

If we put it in SETUP_TRANS0 it will be printed to STDOUT when running the benchmark, or NODE.001_01 when run from IFS.

@wdeconinck isn't there an easy way to have CMake insert this information to the Fortran source through its preprocessor?

**Comment by tlmquintino** [comment]
@samhatfield  rebuild is able to extract the SHA1 from the git repo.
Have a look at how @wdeconinck  does it in the fckit repo. You define a file with .in extension that then gets preprocessed into a source file that you compile.

**Comment by samhatfield** [comment]
Nice advice @tlmquintino - PR #24 opened for your and/or Willem's approval.

**Comment by wdeconinck** [comment]
If you want that in the STDOUT of every run, then that's a good idea.
There was already an offline executable which I created which you can call with "ectrans --info" to get this information out as well.

**Comment by samhatfield** [comment]
I think both are needed. It's useful to get the SHA1 of the ecTrans version in the NODE file.

One issue I'm having with the above commit is that with the benchmark program each MPI rank is printing the Git hash, even though we redirect NOUT to /dev/null for every rank except the first [here](https://github.com/ecmwf-ifs/ectrans/blob/main/src/programs/ectrans-benchmark.F90#L252). Do you know what's going on there @wdeconinck?

**Comment by wdeconinck** [comment]
It looks like in setup_trans0 you are printing to Nout before it is assigned to "kout" argument further down in the same routine. 
Move the printing further down will fix I think.
