### ISSUE TITLE
Floating-point exception for lumi-g, multi-rank CPU version on Frontier (CCE/15.0.0)

### ISSUE THREAD

**Issue by samhatfield** [ecmwf-ifs/ectrans#26]
I am testing the lumi-g branch on Frontier with CCE 15, CPU only on multiple ranks, and I find it gives a floating-point exception somewhere in [`SPNORMC`](https://github.com/ecmwf-ifs/ectrans/blob/lumi-g/src/trans/cpu/internal/spnormc_mod.F90) in the [final call to `specnorm`](https://github.com/ecmwf-ifs/ectrans/blob/lumi-g/src/programs/ectrans-benchmark.F90#L755) after the transform loop. If I comment out the [`write` statement](https://github.com/ecmwf-ifs/ectrans/blob/lumi-g/src/programs/ectrans-benchmark.F90#L736) before this, it proceeds past the crash point.

It works fine:
- If I run on a single rank
- If I disable norm printing (no `--norms`)

My hunch is that we are doing something inconsistent regarding the vertical domain decomposition (e.g. `nflevl`/`nflevg` confusion). Will keep debugging and post updates here.

**Comment by samhatfield** [comment]
I got the order of events wrong - rank 0 is working fine, rank _1_ was the one reporting a segfault. But because we suppress output from all non-zero ranks, I didn't notice.

Not sure exactly what's going on, but I did notice that we perform [this](https://github.com/ecmwf-ifs/ectrans/blob/lumi-g/src/programs/ectrans-benchmark.F90#L718) calculation on all ranks, even though `znormsp` etc. are only non-zero on rank 0. It may be that we are seeing a 0/0 problem.

**Comment by samhatfield** [comment]
Yup that's it. How did we miss those for so long? Are other compilers really that permissive over 0/0 calculations? 😅

**Comment by samhatfield** [comment]
Can confirm the above issue only occurs when the `-Ktrap=fp` Fortran flag is added. The question is, do we want a benchmark that can only run when floating-point exceptions are ignored? If so this issue and the PR can be discarded.

**Comment by wdeconinck** [comment]
No this needs to be merged in. Thanks for your discovery!
