### ISSUE TITLE
Dangling symbolic links in installation include directory

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#68]
I did a build and install of ectrans and saw this in the installation include/ectrans directory:

-rw-r--r--. 1 frwd users 6524 Feb 18 17:07 dir_trans.h
-rw-r--r--. 1 frwd users 6370 Feb 18 17:07 dir_transad.h
-rw-r--r--. 1 frwd users 2084 Feb 18 17:07 dist_grid.h
-rw-r--r--. 1 frwd users 2044 Feb 18 17:07 dist_grid_32.h
-rw-r--r--. 1 frwd users 2205 Feb 18 17:07 dist_spec.h
-rw-r--r--. 1 frwd users 1998 Feb 18 17:07 gath_grid.h
-rw-r--r--. 1 frwd users 2013 Feb 18 17:07 gath_grid_32.h
-rw-r--r--. 1 frwd users 2277 Feb 18 17:07 gath_spec.h
-rw-r--r--. 1 frwd users 1375 Feb 29 17:07 get_current.h
-rw-r--r--. 1 frwd users 2292 Feb 18 17:07 gpnorm_trans.h
-rw-r--r--. 1 frwd users 3030 Feb 29 17:07 ini_spec_dist.h
-rw-r--r--. 1 frwd users 8022 Feb 18 17:07 inv_trans.h
-rw-r--r--. 1 frwd users 7809 Feb 18 17:07 inv_transad.h
-rw-r--r--. 1 frwd users 4558 Feb 18 17:07 setup_trans.h
-rw-r--r--. 1 frwd users 3641 Feb 29 17:07 setup_trans0.h
-rw-r--r--. 1 frwd users 1942 Feb 18 17:07 specnorm.h
-rw-r--r--. 1 frwd users 1450 Feb 18 17:07 sugawc.h
-rw-r--r--. 1 frwd users 1134 Feb 18 17:07 trans_end.h
-rw-r--r--. 1 frwd users 8287 Feb 18 17:07 trans_inq.h
-rw-r--r--. 1 frwd users 1749 Feb 18 17:07 trans_pnm.h
-rw-r--r--. 1 frwd users  570 Feb 18 17:07 trans_release.h
lrwxrwxrwx. 1 frwd users   14 Mar  6 12:59 transi.h -> ../../transi.h
lrwxrwxrwx. 1 frwd users   15 Mar  6 12:59 version.h -> ../../version.h
-rw-r--r--. 1 frwd users 2174 Feb 18 17:07 vordiv_to_uv.h

Those symbolic links are dangling.

**Comment by samhatfield** [comment]
Good spot @DJDavies2.

@wdeconinck - do we need to loop over all files globbed from `include/ectrans` [here](https://github.com/ecmwf-ifs/ectrans/blob/main/src/transi/CMakeLists.txt#L30), detect if they are a symlink, and if so replace with the full path of the pointed-to file?

**Comment by DJDavies2** [comment]
I think there is an easy fix, I can make a PR if you like.

**Comment by wdeconinck** [comment]
Thanks @DJDavies2 for fixing this! Much appreciated.
