### ISSUE TITLE
Runtime failure in DIST_SPEC_CONTROL

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#95]
I have a program which is failing without any sort of error message.  Looking through a core dump it appears to be failing in the call to DIST_SPEC_CONTROL, and this is confirmed by adding write statements.  I know this isn't much to go on, it will be hard for me to produce something to reproduce the problem.

The compiler is gnu 12 on a Cray.  It is related to https://github.com/JCSDA-internal/saber/issues/821.

**Comment by samhatfield** [comment]
Hi @DJDavies2 - thanks for bringing this to our attention. Do you know which line the failure occurs on? Is it a segfault?

Also the link you provided seems to be to a private repository.

**Comment by DJDavies2** [comment]
The line number I think is the call itself to DIST_SPEC_CONTROL from DIST_SPEC; write statements seem to indicate that the code gets as far as the call in DIST_SPEC but doesn't start DIST_SPEC_CONTROL.  I can do more checks though.

Sorry, yes the repo linked to is private, I have no control over that.

**Comment by samhatfield** [comment]
Okay, let us know if you find out anything more. I guess there's nothing we can do on our side until we have a reproducer.

**Comment by DJDavies2** [comment]
Yes, thanks.
